//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKTracker.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> DistributionDate { get; set; }
        public Nullable<int> StockManagementId { get; set; }
        public Nullable<bool> TypeId { get; set; }
        public string BillNo { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual StockManagement StockManagement { get; set; }
        public virtual User User { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Location Location { get; set; }
    }
}
