//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKTracker.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> DistributionDate { get; set; }
        public Nullable<int> StockManagementId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string BillNo { get; set; }
        public string Note { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual StockManagement StockManagement { get; set; }
    }
}
